package org.metamechanists.odysseia.purchase;

public enum ActionType {
    LUCKPERMS_TEMPORARY, LUCKPERMS_PERMANENT, ECONOMY, KIT,
    PROTECTION_STONE, TEMPORARY_PERMISSION, SFMASTER_PASS, SFMASTER_GUIDE, POWER,
    WEAPON, AURA, COSMETIC, NOTIFICATION, ANNOUNCEMENT, MANUAL,
    CONSOLE_COMMAND
}
