package org.metamechanists.odysseia.purchase;

public enum PurchaseState {
    RECEIVED, WAITING_FOR_PLAYER, PROCESSING, PARTIALLY_DELIVERED, COMPLETED,
    FAILED_RETRYABLE, FAILED_MANUAL_REVIEW, REFUNDED, CHARGEBACK
}
